nav:
  首页: /
  关于我: /关于我/
  文章合集: /archives/
  云音乐: https://music.163.com/#/playlist?id=2851221535

social_links:
  github: http://github.com/probberechts/cactus-dark
  mail: mailto:whyouare556@protonmail.com

colorscheme: 'dark'